### PR TITLE
#2541 Fix bug where the OpenAPI generator fails to generate multiple methods for the same path.

### LINKED ISSUE #2541: OpenAPI Generator missing endpoints
**Describe the bug**
I'm testing the new `OpenAPIGen` functionality, and I'm getting output that doesn't match my expectations.
I have two endpoints, one `GET` and one `POST` to the path `/books`.
The `POST` request is the only one that shows up in the generated OpenAPI document.

If I remove the `POST` endpoint, _then_ I do see the `GET` endpoint in the generated OpenAPI document.

**To Reproduce**
Here is an example:
```scala
package dev.zioopenapi.test

import zio.{ExitCode, URIO, ZIO, ZIOAppDefault}
import zio.http.{MediaType, Method, Status}
import zio.http.endpoint.Endpoint
import zio.http.endpoint.openapi.OpenAPIGen
import zio.schema.{DeriveSchema, Schema}

import java.io.{File, FileWriter}
import java.time.Year

final case class Book(
    title: String,
    author: String,
    yearPublished: Year,
)
object Book:
  given Schema[Book] = DeriveSchema.gen
  given Schema[Year] = Schema.primitive[Int].transform(Year.of, _.getValue)

object RestApi:
  final case class GetBooksResponse(books: List[Book])
  private object GetBooksResponse:
    given Schema[GetBooksResponse] = DeriveSchema.gen

  val getBooksEndpoint =
    Endpoint(Method.GET / "books")
      .out[GetBooksResponse](MediaType.application.json)

  val addBookEndpoint =
    Endpoint(Method.POST / "books")
      .in[Book]
      .out[String](Status.Created)

  val endpoints = Vector(getBooksEndpoint, addBookEndpoint)

  val openApiDoc =
    OpenAPIGen
      .fromEndpoints(
        title = "OpenAPI Generator Example",
        version = "0.0.1",
        endpoints
      )
      .toJsonPretty

object OpenApiExample extends ZIOAppDefault:
  override def run: URIO[Any, ExitCode] =
    def openFile(fileName: String)    = ZIO.attemptBlockingIO(new FileWriter(new File(fileName)))
    def closeFile(writer: FileWriter) = ZIO.attemptBlockingIO(writer.close()).orDie
    ZIO
      .acquireReleaseWith(openFile("openapi.json"))(closeFile) { writer =>
        ZIO.attemptBlockingIO(writer.write(RestApi.openApiDoc))
      }
      .exitCode
```
And here is the resulting OpenAPI document:
```json
{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "OpenAPI Generator Example",
    "version" : "0.0.1"
  },
  "paths" : {
    "/books" : {
      "post" : {
        "requestBody" : 
          {
          "content" : {
            "application/json" : {
              "schema" : 
                {
                "$ref" : "#/components/schemas/Book"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : 
            {
            "description" : "",
            "content" : {
              "application/json" : {
                "schema" : 
                  {
                  "type" : 
                    "string"
                }
              }
            }
          }
        },
        "deprecated" : false
      }
    }
  },
  "components" : {
    "schemas" : {
      "Book" : 
        {
        "type" : 
          "object",
        "properties" : {
          "title" : {
            "type" : 
              "string"
          },
          "author" : {
            "type" : 
              "string"
          },
          "yearPublished" : {
            "type" : 
              "integer",
            "format" : "int32"
          }
        },
        "additionalProperties" : 
          true,
        "required" : [
          "title",
          "author",
          "yearPublished"
        ]
      },
      "GetBooksResponse" : 
        {
        "type" : 
          "object",
        "properties" : {
          "books" : {
            "type" : 
              "array",
            "items" : {
              "type" : 
                "object",
              "properties" : {
                "title" : {
                  "type" : 
                    "string"
                },
                "author" : {
                  "type" : 
                    "string"
                },
                "yearPublished" : {
                  "type" : 
                    "integer",
                  "format" : "int32"
                }
              },
              "additionalProperties" : 
                true,
              "required" : [
                "title",
                "author",
                "yearPublished"
              ]
            }
          }
        },
        "additionalProperties" : 
          true,
        "required" : [
          "books"
        ]
      }
    }
  }
}
```
As can be seen, the `GET /books` endpoint is missing.

### PR DESCRIPTION
**Pull request by daharon**
This is an attempt to fix #2541.   
Please make any suggestions regarding unidiomatic or ugly code, or anything I may have overlooked.

### CODE REVIEW

**Comment by daharon** [comment]
I had initially used `groupMapReduce`, which was cleaner.
But I had to change it to work with all the supported Scala versions.

**Review by runtologist — APPROVED** [review]
LGTM

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Good to merge when build is passing. 👍

**Comment by daharon** [comment]
The only failing build is for `Website / Build and Test`.
I figured I shouldn't include changes like that in this PR.

I did run `docs/generateReadme` as the build suggested, but the results contained changes that I wasn't sure about.

**Comment by runtologist** [comment]
@daharon If you are referring to the version change, that's fine. A new RC has been published recently.
LMK if there is something else you are not sure about.

**Pull request merged**
