### PR TITLE
generic filepath was corrected to  actual path

### PR DESCRIPTION
**Pull request by jayachandra27**
File location is corrected to actual path, 

Now GET on localhost:8090/file will display contents of the file as intended.

### CODE REVIEW

**Comment by amitksingh1490** [comment]
remove unnecessary files

**Review by dinojohn — APPROVED** [review]

**Comment by amitksingh1490** [comment]
@jayachandra27 can you please rebase this once

**Comment by jayachandra27** [comment]
Done, can you please try now.

**Comment by amitksingh1490** [comment]
> Done, can you please try now.

image
Still not updated

**Pull request closed without merging**
